[workspace]
members = ["otel-thread-ctx", "custom-labels"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
keywords = ["profiling", "pprof", "polarsignals", "parca"]
homepage = "https://polarsignals.com"
repository = "https://github.com/polarsignals/custom-labels"
readme = "README.md"
